### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by joneshf** [tapeinosyne/elm-microkanren#1]
I am wondering what the status of this library is. Are you planning on publishing this library? If not, would you be against me forking and publishing it?

**Comment by justgage** [comment]
I'm interested in this as well

**Comment by tapeinosyne** [comment]
I apologize for the delay; I must have missed the notification about your issue.

I will update the package to Elm 0.16 and publish it this weekend, although documentation shall defer to the original paper for the foreseeable future.

If you plan to use it, do let me know if anything is amiss.

**Comment by joneshf** [comment]
No worries. I was going to fork and publish this weekend if I didn't hear back by then, so this works great! 

I started building miniKanren on top of this and I wanted to publish that pretty soon, so I need this one up before then :smile: 

The conversion to 0.16 isn't so bad syntactically, but to publish I think every exposed function has to be documented. I'm happy to submit a PR for this if you'd like, so you don't have to do so much work.

**Comment by tapeinosyne** [comment]
Thanks, I appreciate. Unfortunately, it seems that `elm make` and `elm repl` plainly refuse to _compile_, let alone publish, undocumented code, which means that I shall need to write some docs regardless. (If this compiler is an assistant, it certainly is a rather stern one.)

Nevertheless, if you would like to review or improve the documentation later, just say the word and I will ping you here. (With no obligation, of course.)

> I started building miniKanren on top of this and I wanted to publish that pretty soon

Incidentally, this was also my plan, which I hope to resume someday. (There is presumably no risk of name clashes, since my own implementation was called `pteleologic`.)

**Comment by joneshf** [comment]
I don't want us to duplicate work here. We don't really need multiple miniKanren libraries.

What's your general timeline for working on miniKanren? Weeks, months, or just generally far off in the future. I'm not asking so you alter your schedule. I'm asking so I know how to plan mine. If it's a couple weeks or so, I'll noodle about with local stuff. If it's months or longer I'll probably start building something, but happy to merge back with you at a later date if you'd like.

Also, published libraries namespaced, so there can't be clashes like that.

**Comment by tapeinosyne** [comment]
I would not worry about duplicate work: `pteleologic` was started for personal pleasure rather than to serve community interests, and diverges from standard miniKanren in a few significant ways; it is to a good extent an exploration of logic programming for a specific application, and not very suitable for library use.

As for development, I currently have other priorities, and I doubt it will see substantial work for the foreseeable future. Consider my precedent comment a casual if ill-advised remark, with no intent to meddle.

**Comment by joneshf** [comment]
Resolved by: https://github.com/ndr-qef/elm-microkanren/commit/e8dc24eadb3c31efd3d7a1cd5fdb4b7e323041ca
