### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by BrianHicks** [tapeinosyne/elm-microkanren#6]
What's the license of this code? Is it BSD3 like most other Elm programs?

(Background: I'm doing logic programming, specifically I'm trying to extend this to a full minikanren implementation with added error handling. I want to use your code as a base so I don't have to reinvent *all* the wheels but I've got to assume it's not open source right now.)

**Comment by tapeinosyne** [comment]
The license is BSD3, as stated in the [manifest](https://github.com/tapeinosyne/elm-microkanren/blob/master/elm-package.json#L5), but it was remiss of me not to include the actual license file. (To think I even keep a script to automate licensing…)

Thanks for alerting me. I included a copy of BSD3 in 784814e.

**Comment by BrianHicks** [comment]
Thanks for clarifying! :D

**Comment by BrianHicks** [comment]
Actually, can I clear something with you? I'm using your implementation as a base but changing it in some pretty radical ways. Would it satisfy you to have acknowledgement in my project's README? I'm not sure how I can include the license header anyway, since as a published library it'll be included in the doc comment. 🤔

**Comment by BrianHicks** [comment]
Basically, I just want to make sure to give credit where credit is due, and for you not to feel slighted in any way. This is an awesome implementation and I'll be able to stand on the shoulders of giants using it 😀

**Comment by tapeinosyne** [comment]
Thanks for your consideration. Changes and overhauls are expected, since the kind of naïve unification performed by μKanren is rather ill-suited to hefty programs; it's more of an exercise in style.

License headers shouldn't be necessary, unless your project is haunted by legal banshees. As for attribution, there's no need to add anything explicit, particularly if `elm-microkanren` is a hard dependency; otherwise, you can always add a reference somewhere relevant in the source, at your leisure. (Although, to be frank, this library is a very nearly mechanical translation of the original Scheme implementation, and I feel that special mention is hardly due.)

Nevertheless, do ping me when the project is released. I'm sure it will be interesting, and I would welcome the opportunity to take a look.
